apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-tutorial-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-tutorial-nginx
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-nginx
    spec:
      containers:
      - name: kubernetes-tutorial-application
        image: nginx:latest
        ports:
          - containerPort: 80