apiVersion: v1
kind: Service
metadata:
  name: kubernetes-tutorial-node-port-nginx
spec:
  type: NodePort
  selector:
    app: kubernetes-tutorial-nginx   
  ports:   
    - nodePort: 31313
      port: 80
      targetPort: 80
